exports.seed = function(knex) {
  return knex('people_ant').del()
    .then(() => {
      return knex('people_ant').insert([
        {id: 297, lines: 5998, character: 'Antony', origin: 'Ant'},
        {id: 298, lines: 4695, character: 'Cleopatra', origin: 'Ant'},
        {id: 299, lines: 2889, character: 'Octavius', origin: 'Ant'},
        {id: 300, lines: 2436, character: 'Enobarbus', origin: 'Ant'},
        {id: 301, lines: 931, character: 'Pompey', origin: 'Ant'},
        {id: 302, lines: 632, character: 'Charmian', origin: 'Ant'},
        {id: 303, lines: 459, character: 'Menas', origin: 'Ant'},
        {id: 304, lines: 411, character: 'Lepidus', origin: 'Ant'},
        {id: 305, lines: 376, character: 'Agrippa', origin: 'Ant'},
        {id: 306, lines: 286, character: 'Dolabella', origin: 'Ant'},
        {id: 307, lines: 284, character: 'Eros', origin: 'Ant'},
        {id: 308, lines: 267, character: 'Scarus', origin: 'Ant'},
        {id: 309, lines: 255, character: 'Maecenas', origin: 'Ant'},
        {id: 310, lines: 252, character: 'Countryman', origin: 'Ant'},
        {id: 311, lines: 234, character: 'Octavia', origin: 'Ant'},
        {id: 312, lines: 224, character: 'MESSENGERS.X.2', origin: 'Ant'},
        {id: 313, lines: 220, character: 'Ventidius', origin: 'Ant'},
        {id: 314, lines: 211, character: 'Proculeius', origin: 'Ant'},
        {id: 315, lines: 209, character: 'Soothsayer', origin: 'Ant'},
        {id: 316, lines: 207, character: 'Alexas', origin: 'Ant'},
        {id: 317, lines: 182, character: 'Thidias', origin: 'Ant'},
        {id: 318, lines: 165, character: 'Canidius', origin: 'Ant'},
        {id: 319, lines: 160, character: 'Iras', origin: 'Ant'},
        {id: 320, lines: 159, character: 'GUARDS.Dercetus', origin: 'Ant'},
        {id: 321, lines: 128, character: 'Diomedes', origin: 'Ant'},
        {id: 322, lines: 125, character: 'Philo', origin: 'Ant'},
        {id: 323, lines: 118, character: 'Mardian', origin: 'Ant'},
        {id: 324, lines: 107, character: 'Ambassador', origin: 'Ant'},
        {id: 325, lines: 91, character: 'WATCHMEN.Sentry', origin: 'Ant'},
        {id: 326, lines: 87, character: 'SOLDIERS.ANTONY.X.1', origin: 'Ant'},
        {id: 327, lines: 86, character: 'GUARDS.CAESAR.0.1', origin: 'Ant'},
        {id: 328, lines: 83, character: 'MESSENGERS.ANTONY.1', origin: 'Ant'},
        {id: 329, lines: 79, character: 'SOLDIERS.ANTONY.0.1', origin: 'Ant'},
        {id: 330, lines: 77, character: 'SOLDIERS.ANTONY.0.2', origin: 'Ant'},
        {id: 331, lines: 69, character: 'SERVANTS.0.1', origin: 'Ant'},
        {id: 332, lines: 67, character: 'MESSENGERS.CAESAR.2', origin: 'Ant'},
        {id: 333, lines: 67, character: 'Silius', origin: 'Ant'},
        {id: 334, lines: 63, character: 'SOLDIERS.ANTONY.X.3', origin: 'Ant'},
        {id: 335, lines: 62, character: 'SOLDIERS.CAESAR.X.1', origin: 'Ant'},
        {id: 336, lines: 61, character: 'SERVANTS.0.2', origin: 'Ant'},
        {id: 337, lines: 49, character: 'MESSENGERS.CAESAR.1', origin: 'Ant'},
        {id: 338, lines: 39, character: 'Boy', origin: 'Ant'},
        {id: 339, lines: 37, character: 'Egyptian', origin: 'Ant'},
        {id: 340, lines: 36, character: 'GUARDS.0.1', origin: 'Ant'},
        {id: 341, lines: 35, character: 'Demetrius', origin: 'Ant'},
        {id: 342, lines: 29, character: 'SOLDIERS.ANTONY.0.3', origin: 'Ant'},
        {id: 343, lines: 27, character: 'Varrius', origin: 'Ant'},
        {id: 344, lines: 26, character: 'Seleucus', origin: 'Ant'},
        {id: 345, lines: 26, character: 'WATCHMEN.2', origin: 'Ant'},
        {id: 346, lines: 25, character: 'WATCHMEN.1', origin: 'Ant'},
        {id: 347, lines: 24, character: 'CAPTAINS.0.1', origin: 'Ant'},
        {id: 348, lines: 24, character: 'Gallus', origin: 'Ant'},
        {id: 349, lines: 22, character: 'MESSENGERS.ANTONY.3', origin: 'Ant'},
        {id: 350, lines: 21, character: 'GUARDS.CAESAR.1', origin: 'Ant'},
        {id: 351, lines: 20, character: 'SOLDIERS.ANTONY.0.4', origin: 'Ant'},
        {id: 352, lines: 18, character: 'SOLDIERS.ANTONY.X.2', origin: 'Ant'},
        {id: 353, lines: 17, character: 'CAPTAINS', origin: 'Ant'},
        {id: 354, lines: 15, character: 'GUARDS.0.2', origin: 'Ant'},
        {id: 355, lines: 14, character: 'SOLDIERS.ANTONY', origin: 'Ant'},
        {id: 356, lines: 13, character: 'MESSENGERS.X.3', origin: 'Ant'},
        {id: 357, lines: 11, character: 'ATTENDANTS.CAESAR', origin: 'Ant'},
        {id: 358, lines: 11, character: 'GUARDS.0.3', origin: 'Ant'},
        {id: 359, lines: 9, character: 'GUARDS.CAESAR.0.2', origin: 'Ant'},
        {id: 360, lines: 9, character: 'GUARDS', origin: 'Ant'},
        {id: 361, lines: 9, character: 'MESSENGERS.ANTONY.2', origin: 'Ant'},
        {id: 362, lines: 7, character: 'SERVANTS.X.2', origin: 'Ant'},
        {id: 363, lines: 6, character: 'MESSENGERS.X.1', origin: 'Ant'},
        {id: 364, lines: 6, character: 'MESSENGERS.X.5', origin: 'Ant'},
        {id: 365, lines: 4, character: 'MESSENGERS.X.4', origin: 'Ant'},
        {id: 366, lines: 4, character: 'SERVANTS.X.1', origin: 'Ant'},
        {id: 367, lines: 3, character: 'ATTENDANTS.ANTONY', origin: 'Ant'},
        {id: 368, lines: 3, character: 'LADIES', origin: 'Ant'},
        {id: 369, lines: 3, character: 'SERVANTS', origin: 'Ant'},
        {id: 370, lines: 2, character: 'Taurus', origin: 'Ant'}
      ])
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('people_ant_id_seq', (SELECT MAX(id) FROM people_ant))"
      )
    })
}
